services:
  - type: web
    name: telegram-status-checker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /mnt/cache/.playwright
